//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhPham.Web.BepNhaBan.AppAdmin.AdminControls {
    
    
    public partial class IndexUC {
    }
}
