//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace bnb.approot.AppAdmin.Agent.Delievery
{
    
    
    public partial class Index {
        
        /// <summary>
        /// IndexUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MinhPham.Web.BepNhaBan.AppAdmin.Agent.Delievery.IndexUC IndexUC1;
    }
}
