//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhPham.Web.BepNhaBan.AppAdmin.TinhNangChucNang {
    
    
    public partial class TinhNang {
        
        /// <summary>
        /// TinhNangUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MinhPham.Web.BepNhaBan.AppAdmin.TinhNangChucNang.TinhNangUC TinhNangUC1;
    }
}
