//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bản tin.
        /// </summary>
        internal static string article_title {
            get {
                return ResourceManager.GetString("article_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình menu - Bếp Nhà Bạn.
        /// </summary>
        internal static string ConfigMenu {
            get {
                return ResourceManager.GetString("ConfigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách chủ đề.
        /// </summary>
        internal static string content_title {
            get {
                return ResourceManager.GetString("content_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lập cảnh báo khách hàng - Bếp Nhà Bạn.
        /// </summary>
        internal static string CustomerNote {
            get {
                return ResourceManager.GetString("CustomerNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Bếp Nhà Bạn.
        /// </summary>
        internal static string ProductDetail_UC_LoadSanPham____Bếp_Nhà_Bạn {
            get {
                return ResourceManager.GetString("ProductDetail_UC_LoadSanPham____Bếp_Nhà_Bạn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin sản phẩm - Bếp Nhà Bạn.
        /// </summary>
        internal static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách dịch vụ .
        /// </summary>
        internal static string service_title {
            get {
                return ResourceManager.GetString("service_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập hệ thống - Bếp Nhà Bạn.
        /// </summary>
        internal static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        internal static string title_separator {
            get {
                return ResourceManager.GetString("title_separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bộ phận nước tinh khiết.
        /// </summary>
        internal static string Water_Title {
            get {
                return ResourceManager.GetString("Water_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-SFIS Co.,Ltd.
        /// </summary>
        internal static string website_name {
            get {
                return ResourceManager.GetString("website.name", resourceCulture);
            }
        }
    }
}
