//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Permission {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Permission() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Permission", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_Them.
        /// </summary>
        internal static string KhachHang_Them {
            get {
                return ResourceManager.GetString("KhachHang_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiNhanh_Sua.
        /// </summary>
        internal static string strChiNhanh_Sua {
            get {
                return ResourceManager.GetString("strChiNhanh_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiNhanh_Them.
        /// </summary>
        internal static string strChiNhanh_Them {
            get {
                return ResourceManager.GetString("strChiNhanh_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiNhanh_Xem.
        /// </summary>
        internal static string strChiNhanh_Xem {
            get {
                return ResourceManager.GetString("strChiNhanh_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChiNhanh_Xoa.
        /// </summary>
        internal static string strChiNhanh_Xoa {
            get {
                return ResourceManager.GetString("strChiNhanh_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DanhMuc_Sua.
        /// </summary>
        internal static string strDanhMuc_Sua {
            get {
                return ResourceManager.GetString("strDanhMuc_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DanhMuc_Them.
        /// </summary>
        internal static string strDanhMuc_Them {
            get {
                return ResourceManager.GetString("strDanhMuc_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DanhMuc_Xem.
        /// </summary>
        internal static string strDanhMuc_Xem {
            get {
                return ResourceManager.GetString("strDanhMuc_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DanhMuc_Xoa.
        /// </summary>
        internal static string strDanhMuc_Xoa {
            get {
                return ResourceManager.GetString("strDanhMuc_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNangChucNang_Sua.
        /// </summary>
        internal static string strgTinhNangChucNang_Sua {
            get {
                return ResourceManager.GetString("strgTinhNangChucNang_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_CanhBao.
        /// </summary>
        internal static string strKhachHang_CanhBao {
            get {
                return ResourceManager.GetString("strKhachHang_CanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_DoTim.
        /// </summary>
        internal static string strKhachHang_DoTim {
            get {
                return ResourceManager.GetString("strKhachHang_DoTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_Sua.
        /// </summary>
        internal static string strKhachHang_Sua {
            get {
                return ResourceManager.GetString("strKhachHang_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_Them.
        /// </summary>
        internal static string strKhachHang_Them {
            get {
                return ResourceManager.GetString("strKhachHang_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_TimKiem.
        /// </summary>
        internal static string strKhachHang_TimKiem {
            get {
                return ResourceManager.GetString("strKhachHang_TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_Xem.
        /// </summary>
        internal static string strKhachHang_Xem {
            get {
                return ResourceManager.GetString("strKhachHang_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KhachHang_Xoa.
        /// </summary>
        internal static string strKhachHang_Xoa {
            get {
                return ResourceManager.GetString("strKhachHang_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC_Sua.
        /// </summary>
        internal static string strNCC_Sua {
            get {
                return ResourceManager.GetString("strNCC_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC_Them.
        /// </summary>
        internal static string strNCC_Them {
            get {
                return ResourceManager.GetString("strNCC_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC_Xem.
        /// </summary>
        internal static string strNCC_Xem {
            get {
                return ResourceManager.GetString("strNCC_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC_Xoa.
        /// </summary>
        internal static string strNCC_Xoa {
            get {
                return ResourceManager.GetString("strNCC_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhanVien_Sua.
        /// </summary>
        internal static string strNhanVien_Sua {
            get {
                return ResourceManager.GetString("strNhanVien_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhanVien_Them.
        /// </summary>
        internal static string strNhanVien_Them {
            get {
                return ResourceManager.GetString("strNhanVien_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhanVien_Xem.
        /// </summary>
        internal static string strNhanVien_Xem {
            get {
                return ResourceManager.GetString("strNhanVien_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhanVien_Xoa.
        /// </summary>
        internal static string strNhanVien_Xoa {
            get {
                return ResourceManager.GetString("strNhanVien_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomChucNang_Sua.
        /// </summary>
        internal static string strNhomChucNang_Sua {
            get {
                return ResourceManager.GetString("strNhomChucNang_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomChucNang_Them.
        /// </summary>
        internal static string strNhomChucNang_Them {
            get {
                return ResourceManager.GetString("strNhomChucNang_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomChucNang_Xem.
        /// </summary>
        internal static string strNhomChucNang_Xem {
            get {
                return ResourceManager.GetString("strNhomChucNang_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomChucNang_Xoa.
        /// </summary>
        internal static string strNhomChucNang_Xoa {
            get {
                return ResourceManager.GetString("strNhomChucNang_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomNhanVien_Sua.
        /// </summary>
        internal static string strNhomNhanVien_Sua {
            get {
                return ResourceManager.GetString("strNhomNhanVien_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomNhanVien_Them.
        /// </summary>
        internal static string strNhomNhanVien_Them {
            get {
                return ResourceManager.GetString("strNhomNhanVien_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomNhanVien_Xem.
        /// </summary>
        internal static string strNhomNhanVien_Xem {
            get {
                return ResourceManager.GetString("strNhomNhanVien_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomNhanVien_Xoa.
        /// </summary>
        internal static string strNhomNhanVien_Xoa {
            get {
                return ResourceManager.GetString("strNhomNhanVien_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomThanhVien_Sua.
        /// </summary>
        internal static string strNhomThanhVien_Sua {
            get {
                return ResourceManager.GetString("strNhomThanhVien_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomThanhVien_Them.
        /// </summary>
        internal static string strNhomThanhVien_Them {
            get {
                return ResourceManager.GetString("strNhomThanhVien_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomThanhVien_Xem.
        /// </summary>
        internal static string strNhomThanhVien_Xem {
            get {
                return ResourceManager.GetString("strNhomThanhVien_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NhomThanhVien_Xoa.
        /// </summary>
        internal static string strNhomThanhVien_Xoa {
            get {
                return ResourceManager.GetString("strNhomThanhVien_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhieuNhapKho_Sua.
        /// </summary>
        internal static string strPhieuNhapKho_Sua {
            get {
                return ResourceManager.GetString("strPhieuNhapKho_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhieuNhapKho_Them.
        /// </summary>
        internal static string strPhieuNhapKho_Them {
            get {
                return ResourceManager.GetString("strPhieuNhapKho_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhieuNhapKho_Xem.
        /// </summary>
        internal static string strPhieuNhapKho_Xem {
            get {
                return ResourceManager.GetString("strPhieuNhapKho_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhieuNhapKho_Xoa.
        /// </summary>
        internal static string strPhieuNhapKho_Xoa {
            get {
                return ResourceManager.GetString("strPhieuNhapKho_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_CanhBao.
        /// </summary>
        internal static string strSanPham_CanhBao {
            get {
                return ResourceManager.GetString("strSanPham_CanhBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_DoTim.
        /// </summary>
        internal static string strSanPham_DoTim {
            get {
                return ResourceManager.GetString("strSanPham_DoTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_Sua.
        /// </summary>
        internal static string strSanPham_Sua {
            get {
                return ResourceManager.GetString("strSanPham_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_Them.
        /// </summary>
        internal static string strSanPham_Them {
            get {
                return ResourceManager.GetString("strSanPham_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_ThietLapGia.
        /// </summary>
        internal static string strSanPham_ThietLapGia {
            get {
                return ResourceManager.GetString("strSanPham_ThietLapGia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_TimKiem.
        /// </summary>
        internal static string strSanPham_TimKiem {
            get {
                return ResourceManager.GetString("strSanPham_TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_Xem.
        /// </summary>
        internal static string strSanPham_Xem {
            get {
                return ResourceManager.GetString("strSanPham_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanPham_Xoa.
        /// </summary>
        internal static string strSanPham_Xoa {
            get {
                return ResourceManager.GetString("strSanPham_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThanhVien_Sua.
        /// </summary>
        internal static string strThanhVien_Sua {
            get {
                return ResourceManager.GetString("strThanhVien_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThanhVien_Them.
        /// </summary>
        internal static string strThanhVien_Them {
            get {
                return ResourceManager.GetString("strThanhVien_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThanhVien_Xem.
        /// </summary>
        internal static string strThanhVien_Xem {
            get {
                return ResourceManager.GetString("strThanhVien_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThanhVien_Xoa.
        /// </summary>
        internal static string strThanhVien_Xoa {
            get {
                return ResourceManager.GetString("strThanhVien_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThuongHieu_Sua.
        /// </summary>
        internal static string strThuongHieu_Sua {
            get {
                return ResourceManager.GetString("strThuongHieu_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThuongHieu_Them.
        /// </summary>
        internal static string strThuongHieu_Them {
            get {
                return ResourceManager.GetString("strThuongHieu_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThuongHieu_Xem.
        /// </summary>
        internal static string strThuongHieu_Xem {
            get {
                return ResourceManager.GetString("strThuongHieu_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThuongHieu_Xoa.
        /// </summary>
        internal static string strThuongHieu_Xoa {
            get {
                return ResourceManager.GetString("strThuongHieu_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNangChucNang_Them.
        /// </summary>
        internal static string strTinhNangChucNang_Them {
            get {
                return ResourceManager.GetString("strTinhNangChucNang_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNangChucNang_Xem.
        /// </summary>
        internal static string strTinhNangChucNang_Xem {
            get {
                return ResourceManager.GetString("strTinhNangChucNang_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNangChucNang_Xoa.
        /// </summary>
        internal static string strTinhNangChucNang_Xoa {
            get {
                return ResourceManager.GetString("strTinhNangChucNang_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNang_Sua.
        /// </summary>
        internal static string strTinhNang_Sua {
            get {
                return ResourceManager.GetString("strTinhNang_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNang_Them.
        /// </summary>
        internal static string strTinhNang_Them {
            get {
                return ResourceManager.GetString("strTinhNang_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNang_Xem.
        /// </summary>
        internal static string strTinhNang_Xem {
            get {
                return ResourceManager.GetString("strTinhNang_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinhNang_Xoa.
        /// </summary>
        internal static string strTinhNang_Xoa {
            get {
                return ResourceManager.GetString("strTinhNang_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TonKho_Xem.
        /// </summary>
        internal static string strTonKho_Xem {
            get {
                return ResourceManager.GetString("strTonKho_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraTienNCC_Sua.
        /// </summary>
        internal static string strTraTienNCC_Sua {
            get {
                return ResourceManager.GetString("strTraTienNCC_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraTienNCC_Them.
        /// </summary>
        internal static string strTraTienNCC_Them {
            get {
                return ResourceManager.GetString("strTraTienNCC_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraTienNCC_Xem.
        /// </summary>
        internal static string strTraTienNCC_Xem {
            get {
                return ResourceManager.GetString("strTraTienNCC_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraTienNCC_Xoa.
        /// </summary>
        internal static string strTraTienNCC_Xoa {
            get {
                return ResourceManager.GetString("strTraTienNCC_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse_Sua.
        /// </summary>
        internal static string strWarehouse_Sua {
            get {
                return ResourceManager.GetString("strWarehouse_Sua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse_Them.
        /// </summary>
        internal static string strWarehouse_Them {
            get {
                return ResourceManager.GetString("strWarehouse_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse_Xem.
        /// </summary>
        internal static string strWarehouse_Xem {
            get {
                return ResourceManager.GetString("strWarehouse_Xem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse_Xoa.
        /// </summary>
        internal static string strWarehouse_Xoa {
            get {
                return ResourceManager.GetString("strWarehouse_Xoa", resourceCulture);
            }
        }
    }
}
