//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace bnb.approot.AppAdmin.Employee {
    
    
    public partial class NhanVien_Add {
        
        /// <summary>
        /// NhanVien_AddUC1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::bnb.approot.AppAdmin.Employee.NhanVien_AddUC NhanVien_AddUC1;
    }
}
